name: CI

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.71
          components: rustfmt, clippy

      - name: Build
        run: cargo build --verbose

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: "clippy --all"
        run: cargo clippy --all --tests --all-features --no-deps

      - name: Run tests
        run: cargo test --verbose
